language: ruby
rvm: 2.6.2
install:
  - |
      export ECLIPSE_EXE=$HOME/eclipse-cache/eclipse/eclipse
      if [ ! -f "$ECLIPSE_EXE" ]; then
        wget -O eclipse.tar.gz https://archive.eclipse.org/eclipse/downloads/drops4/R-4.5.2-201602121500/eclipse-SDK-4.5.2-linux-gtk-x86_64.tar.gz
        tar -C $HOME/eclipse-cache -xzf eclipse.tar.gz
      fi
  - tool/jt.rb install jvmci
  - tool/jt.rb mx sforceimports
  - tool/jt.rb build
  - gem install rubocop:0.66.0
script:
  - tool/jt.rb lint
cache:
  directories:
    - $HOME/.mx/cache
    - $HOME/eclipse-cache
