---
containers:
  debian:
    includes_source: false
    workdir: /build/truffleruby-shopify
    environment: build
    build:
      tag_using_path: .shopify-build/Dockerfile.debian
      env:
        PIPA_PIPELINE_TEMPLATE: dockerfile
        PIPA_DOCKERFILE: .shopify-build/Dockerfile.debian
  macos:
    anka: macos-xcode11.1:latest
  upload:
    environment: upload
    includes_source: false
    build:
      tag_using_path: .shopify-build/Dockerfile.upload
      env:
        PIPA_PIPELINE_TEMPLATE: dockerfile
        PIPA_DOCKERFILE: .shopify-build/Dockerfile.upload
  packagecloud:
    docker: gcr.io/shopify-docker-images/ci/ruby26:Ruby-2.6.5-Node-10.16.3-Yarn-1.13.0

shared:
  truffle_run: &truffle_run
    timeout: 30m
    high_concurrency: true
    import_artifacts:
    - pattern: '*.tar.gz'
      into: .shopify-build/artifacts
  language_specs: &language_specs
    <<: *truffle_run
    label: "Run Ruby language, command-line, and security specs"
    run: .shopify-build/test-specs.sh :language :command_line :security
  core_specs: &core_specs
    <<: *truffle_run
    label: Run Ruby core specs
    run: .shopify-build/test-specs.sh :core
  library_specs: &library_specs
    <<: *truffle_run
    label: Run Ruby library specs
    run: .shopify-build/test-specs.sh :library :library_cext
  capi_specs: &capi_specs
    <<: *truffle_run
    label: Run Ruby C extension specs
    run: .shopify-build/test-specs.sh :capi
  truffle_specs: &truffle_specs
    <<: *truffle_run
    label: Run Truffle specs
    run: .shopify-build/test-specs.sh :truffle :truffle_capi
  compiler_tests: &compiler_tests
    <<: *truffle_run
    label: Run compiler tests
    run: .shopify-build/test-compiler.sh
  addressable_test: &addressable_test
    <<: *truffle_run
    label: Run addressable tests
    run: .shopify-build/test-gem.sh addressable
  browser_sniffer_test: &browser_sniffer_test
    <<: *truffle_run
    label: Run browser_sniffer tests
    run: .shopify-build/test-gem.sh browser_sniffer
  cacheable_test: &cacheable_test
    <<: *truffle_run
    label: Run cacheable tests
    run: .shopify-build/test-gem.sh cacheable
  i18n_test: &i18n_test
    <<: *truffle_run
    label: Run i18n tests
    run: .shopify-build/test-gem.sh i18n
  json_test: &json_test
    <<: *truffle_run
    label: Run json tests
    run: .shopify-build/test-gem.sh json
  liquid_test: &liquid_test
    <<: *truffle_run
    label: Run liquid tests
    run: .shopify-build/test-gem.sh liquid
  measured_test: &measured_test
    <<: *truffle_run
    label: Run measured tests
    run: .shopify-build/test-gem.sh measured
  minitest_test: &minitest_test
    <<: *truffle_run
    label: Run minitest tests
    run: .shopify-build/test-gem.sh minitest
  mocha_test: &mocha_test
    <<: *truffle_run
    label: Run mocha tests
    run: .shopify-build/test-gem.sh mocha
  money_test: &money_test
    <<: *truffle_run
    label: Run money tests
    run: .shopify-build/test-gem.sh money
  mysql2_test: &mysql2_test
    <<: *truffle_run
    label: Run mysql2 basic tests
    services:
      mysql: '5.7'
    run: .shopify-build/test-gem.sh mysql2
  nokogiri_test: &nokogiri_test
    <<: *truffle_run
    label: Install nokogiri
    run: .shopify-build/test-gem.sh nokogiri
  oj_test: &oj_test
    <<: *truffle_run
    label: Install oj
    run: .shopify-build/test-gem.sh oj
  nokogumbo_test: &nokogumbo_test
    <<: *truffle_run
    label: Install nokogumbo
    run: .shopify-build/test-gem.sh nokogumbo
  protobuf_test: &protobuf_test
    <<: *truffle_run
    label: Run google-protobuf tests
    run: .shopify-build/test-gem.sh protobuf
  semian_test: &semian_test
    <<: *truffle_run
    label: Build semian
    run: .shopify-build/test-gem.sh semian
  snappy_test: &snappy_test
    <<: *truffle_run
    label: Run snappy tests
    run: .shopify-build/test-gem.sh snappy
  puma_test: &puma_test
    <<: *truffle_run
    label: Run puma tests
    run: .shopify-build/test-gem.sh puma
  statsd_instrument_test: &statsd_instrument_test
    <<: *truffle_run
    label: Run statsd-instrument tests
    run: .shopify-build/test-gem.sh statsd-instrument
  webauthn_ruby_test: &webauthn_ruby_test
    <<: *truffle_run
    label: Run webauthn-ruby tests
    run: .shopify-build/test-gem.sh webauthn-ruby
  zeitwerk_test: &zeitwerk_test
    <<: *truffle_run
    label: Run zeitwerk tests
    run: .shopify-build/test-gem.sh zeitwerk
  storefront_renderer_test: &storefront_renderer_test
    timeout: 60m
    high_concurrency: true
    services:
      mysql: '5.7'
      memcached: 'alpine'
      redis:
        image: redis:alpine
        command: redis-server
      toxiproxy:
        image: shopify/toxiproxy
    import_artifacts:
    - pattern: '*.tar.gz'
      into: .shopify-build/artifacts
    env:
      TOXIPROXY_HOST: 'toxiproxy'
      REDIS_SERVER: redis:6379

pipelines:

  truffleruby-shopify-lint:
    default_container: debian
    steps:
      - label: Run lint checks
        timeout: 30m
        git:
          history: shallow
        run: .shopify-build/lint.sh

  truffleruby-shopify-debian:
    default_container: debian
    steps:
      - label: Build TruffleRuby on Debian
        high_concurrency: true
        timeout: 90m
        git:
          history: shallow
        artifact_paths:
          - path: .shopify-build/artifacts
            required: true
        run: .shopify-build/build.sh
      - wait
      - <<: *language_specs
      - <<: *core_specs
      - <<: *library_specs
      - <<: *capi_specs
      - <<: *truffle_specs
      - <<: *compiler_tests
      - <<: *addressable_test
      - <<: *browser_sniffer_test
      - <<: *cacheable_test
      - <<: *i18n_test
      - <<: *json_test
      - <<: *liquid_test
      - <<: *measured_test
      - <<: *minitest_test
      - <<: *mysql2_test
      - <<: *mocha_test
      - <<: *money_test
      - <<: *nokogiri_test
      - <<: *nokogumbo_test
      - <<: *oj_test
      - <<: *puma_test
      - <<: *semian_test
      - <<: *snappy_test
      - <<: *statsd_instrument_test
      - <<: *protobuf_test
      - <<: *webauthn_ruby_test
      - <<: *zeitwerk_test
      - wait
      - block: Make and upload Debian package to Package Cloud
      - label: "make and publish debian package out of build/"
        <<: *truffle_run
        container: packagecloud
        ejson: .shopify-build/package_cloud.ejson
        run:
          - gem install package_cloud
          - .shopify-build/make-debian-package.sh

  truffleruby-shopify-macos:
    default_container: macos
    steps:
      - label: Build TruffleRuby on macOS
        timeout: 90m
        git:
          history: shallow
        artifact_paths:
          - path: .shopify-build/artifacts
            required: true
        run: .shopify-build/build.sh
      - wait
      - <<: *language_specs
      - <<: *core_specs
      - <<: *library_specs
      - <<: *capi_specs
      - <<: *truffle_specs
      - <<: *compiler_tests
      - <<: *addressable_test
      - <<: *browser_sniffer_test
      - <<: *cacheable_test
      - <<: *i18n_test
      - <<: *json_test
      - <<: *liquid_test
      - <<: *measured_test
      - <<: *minitest_test
      # - <<: *mysql2_test not run as the MySQL service doesn't seem to work on macOS
      - <<: *mocha_test
      - <<: *money_test
      - <<: *nokogiri_test
      - <<: *nokogumbo_test
      - <<: *oj_test
      - <<: *puma_test
      - <<: *semian_test
      - <<: *snappy_test
      - <<: *statsd_instrument_test
      - <<: *protobuf_test
      - <<: *webauthn_ruby_test
      - <<: *zeitwerk_test
      - block: Release to dev
      - label: Upload to S3 and send PR to Shopify/dev
        timeout: 30m
        container: upload
        import_artifacts:
        - pattern: '*.tar.gz'
          into: .shopify-build/artifacts
        run:
          - .shopify-build/prepare-package.sh
          - git clone git@github.com:Shopify/ruby-builder.git
          - mkdir ruby-builder/rubies
          - mv rubies/truffleruby*.tgz ruby-builder/rubies/
          - cd ruby-builder
          - gem install bundler -v "$(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -n 1)"
          - bundle install --without test --without development
          - bundle exec ruby bin/upload_bins_for_dev

  truffleruby-shopify-storefront-renderer:
    default_container: debian
    steps:
      - label: Build TruffleRuby on Debian
        high_concurrency: true
        timeout: 90m
        git:
          history: shallow
        artifact_paths:
          - path: .shopify-build/artifacts
            required: true
        run: .shopify-build/build.sh
      - wait
      - label: Run storefront_renderer test:unit
        <<: *storefront_renderer_test
        run: .shopify-build/test-gem.sh storefront-renderer-test-unit
      - label: Run storefront_renderer test:shared
        <<: *storefront_renderer_test
        run: .shopify-build/test-gem.sh storefront-renderer-test-shared
      - label: Run storefront_renderer test:liquid
        <<: *storefront_renderer_test
        run: .shopify-build/test-gem.sh storefront-renderer-test-liquid
