---
containers:
  debian:
    includes_source: false
    workdir: /build/truffleruby-shopify
    environment: build
    build:
      tag_using_path: .shopify-build/Dockerfile.debian
      env:
        PIPA_PIPELINE_TEMPLATE: dockerfile
        PIPA_DOCKERFILE: .shopify-build/Dockerfile.debian
  macos:
    anka: macos-xcode11.1:latest
  upload:
    environment: upload
    includes_source: false
    build:
      tag_using_path: .shopify-build/Dockerfile.upload
      env:
        PIPA_PIPELINE_TEMPLATE: dockerfile
        PIPA_DOCKERFILE: .shopify-build/Dockerfile.upload

shared:
  truffle_run: &truffle_run
    timeout: 30m
    cache:
      - path: .shopify-build/build
        required: true
        inherited: false
        upload: false
        scope: "platform-${SHOPIFY_BUILD_PIPELINE_SLUG}"
  language_specs: &language_specs
    <<: *truffle_run
    label: "Run Ruby language, command-line, and security specs"
    run: .shopify-build/test-specs.sh :language :command_line :security
  core_specs: &core_specs
    <<: *truffle_run
    label: Run Ruby core specs
    run: .shopify-build/test-specs.sh :core
  library_specs: &library_specs
    <<: *truffle_run
    label: Run Ruby library specs
    run: .shopify-build/test-specs.sh :library :library_cext
  capi_specs: &capi_specs
    <<: *truffle_run
    label: Run Ruby C extension specs
    run: .shopify-build/test-specs.sh :capi
  truffle_specs: &truffle_specs
    <<: *truffle_run
    label: Run Truffle specs
    run: .shopify-build/test-specs.sh :truffle :truffle_capi
  addressable_test: &addressable_test
    <<: *truffle_run
    label: Run addressable tests
    run: .shopify-build/test-gem.sh addressable
  browser_sniffer_test: &browser_sniffer_test
    <<: *truffle_run
    label: Run browser_sniffer tests
    run: .shopify-build/test-gem.sh browser_sniffer
  cacheable_test: &cacheable_test
    <<: *truffle_run
    label: Run cacheable tests
    run: .shopify-build/test-gem.sh cacheable
  i18n_test: &i18n_test
    <<: *truffle_run
    label: Run i18n tests
    run: .shopify-build/test-gem.sh i18n
  liquid_test: &liquid_test
    <<: *truffle_run
    label: Run liquid tests
    run: .shopify-build/test-gem.sh liquid
  measured_test: &measured_test
    <<: *truffle_run
    label: Run measured tests
    run: .shopify-build/test-gem.sh measured
  minitest_test: &minitest_test
    <<: *truffle_run
    label: Run minitest tests
    run: .shopify-build/test-gem.sh minitest
  money_test: &money_test
    <<: *truffle_run
    label: Run money tests
    run: .shopify-build/test-gem.sh money
  nokogiri_test: &nokogiri_test
    <<: *truffle_run
    label: Install nokogiri
    run: .shopify-build/test-gem.sh nokogiri
  nokogumbo_test: &nokogumbo_test
    <<: *truffle_run
    label: Install nokogumbo
    run: .shopify-build/test-gem.sh nokogumbo
  protobuf_test: &protobuf_test
    <<: *truffle_run
    label: Run google-protobuf tests
    run: .shopify-build/test-gem.sh protobuf
  snappy_test: &snappy_test
    <<: *truffle_run
    label: Run snappy tests
    run: .shopify-build/test-gem.sh snappy
  puma_test: &puma_test
    <<: *truffle_run
    label: Run puma tests
    run: .shopify-build/test-gem.sh puma
  statsd_instrument_test: &statsd_instrument_test
    <<: *truffle_run
    label: Run statsd-instrument tests
    run: .shopify-build/test-gem.sh statsd-instrument
  storefront_renderer: &storefront_renderer
    <<: *truffle_run
    label: Install storefront_renderer
    run: .shopify-build/test-gem.sh storefront-renderer
  zeitwerk_test: &zeitwerk_test
    <<: *truffle_run
    label: Run zeitwerk tests
    run: .shopify-build/test-gem.sh zeitwerk

pipelines:
  truffleruby-shopify-debian:
    default_container: debian
    steps:
      - label: "Build TruffleRuby on Debian"
        high_concurrency: true
        timeout: 90m
        git:
          history: shallow
        cache:
          - path: .shopify-build/build
            inherited: false
            scope: "platform-${SHOPIFY_BUILD_PIPELINE_SLUG}"
        run:
          - .shopify-build/build.sh
      - wait
      - <<: *language_specs
      - <<: *core_specs
      - <<: *library_specs
      - <<: *capi_specs
      - <<: *truffle_specs
      - <<: *addressable_test
      - <<: *browser_sniffer_test
      - <<: *cacheable_test
      - <<: *i18n_test
      - <<: *liquid_test
      - <<: *measured_test
      - <<: *minitest_test
      - <<: *money_test
      - <<: *nokogiri_test
      - <<: *nokogumbo_test
      - <<: *snappy_test
      - <<: *puma_test
      - <<: *statsd_instrument_test
      - <<: *protobuf_test
      - <<: *storefront_renderer
      - <<: *zeitwerk_test
      - block: Produce a tarball artifact
      - <<: *truffle_run
        label: Package
        run: .shopify-build/package.sh
        artifact_paths:
          - .shopify-build/artifacts

  truffleruby-shopify-macos:
    default_container: macos
    steps:
      - label: Build TruffleRuby on macOS
        timeout: 90m
        git:
          history: shallow
        cache:
          - path: .shopify-build/build
            inherited: false
            scope: "platform-${SHOPIFY_BUILD_PIPELINE_SLUG}"
        run:
          - .shopify-build/build.sh
      - wait
      - <<: *language_specs
      - <<: *core_specs
      - <<: *library_specs
      - <<: *capi_specs
      - <<: *truffle_specs
      - <<: *addressable_test
      - <<: *browser_sniffer_test
      - <<: *cacheable_test
      - <<: *i18n_test
      - <<: *liquid_test
      - <<: *measured_test
      - <<: *minitest_test
      - <<: *money_test
      - <<: *nokogiri_test
      - <<: *nokogumbo_test
      - <<: *snappy_test
      - <<: *puma_test
      - <<: *statsd_instrument_test
      - <<: *protobuf_test
      - <<: *storefront_renderer
      - <<: *zeitwerk_test
      - block: Produce a tarball artifact
      - <<: *truffle_run
        label: Package
        run: .shopify-build/package.sh
        artifact_paths:
          - .shopify-build/artifacts
      - block: Release to dev
      - label: Upload to S3 and send PR to Shopify/dev
        timeout: 30m
        container: upload
        cache:
          - path: .shopify-build/build
            required: true
            inherited: false
            upload: false
            scope: "platform-${SHOPIFY_BUILD_PIPELINE_SLUG}"
        run:
          - .shopify-build/prepare-package.sh
          - git clone git@github.com:Shopify/ruby-builder.git
          - mkdir ruby-builder/rubies
          - mv rubies/truffleruby*.tgz ruby-builder/rubies/
          - cd ruby-builder
          - gem install bundler -v "$(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -n 1)"
          - bundle install --without test --without development
          - bundle exec ruby bin/upload_bins_for_dev
