rpm_packages: &rpm_packages
  locale:
  curl: curl
  git: git
  tar: tar gzip
  specs: which findutils
  zlib: zlib-devel
  openssl: openssl-devel
  cext: gcc make
  source: file gcc-c++ python ruby

deb_packages: &deb_packages
  locale: locales
  curl: curl
  git: git
  tar:
  specs: netbase
  zlib: libz-dev
  openssl: libssl-dev
  cext: gcc libxml2 make
  source: file g++ python ruby

ol7:
  base: oraclelinux:7-slim
  set-locale:
    - ENV LANG=en_US.UTF-8
  install: RUN yum install -y
  <<: *rpm_packages

fedora28:
  base: fedora:28
  set-locale:
    - ENV LANG=en_US.UTF-8
  install: RUN dnf install -y
  <<: *rpm_packages

ubuntu1804:
  base: ubuntu:18.04
  set-locale:
    - RUN locale-gen en_US.UTF-8
    - ENV LANG=en_US.UTF-8
  install: RUN apt-get update && apt-get install -y
  <<: *deb_packages

ubuntu1604:
  base: ubuntu:16.04
  set-locale:
    - RUN locale-gen en_US.UTF-8
    - ENV LANG=en_US.UTF-8
  install: RUN apt-get update && apt-get install -y
  <<: *deb_packages
